"""M10 build script — produce the single-file `eds` binary via PyInstaller.

Bakes the version into eds/_version.py (from $GIT_SHA, an arg, or `git rev-parse`), runs `pyinstaller eds.spec`,
and packages dist/eds[.exe] into the goreleaser-style archive dist/eds_<Platform>_<arch>.{zip|tar.gz} — the SAME
name + container the `download` command (eds.upgrade.build_release_urls + _extract) and the Go release pipeline
use: a .zip with an inner `eds.exe` on Windows, else a .tar.gz with an inner member named `eds`. Run from the repo
root: `python packaging/build.py [version]`.
"""

from __future__ import annotations

import os
import platform
import subprocess
import sys
import tarfile
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# goreleaser arch mapping (mirrors eds/upgrade.build_release_urls + .goreleaser.yaml).
_ARCH = {"amd64": "x86_64", "x86_64": "x86_64", "386": "i386", "i386": "i386", "arm64": "arm64", "aarch64": "arm64"}


def _resolve_version(argv: list[str]) -> str:
    if len(argv) > 1 and argv[1]:
        return argv[1]
    env = os.environ.get("GIT_SHA")
    if env:
        return env
    try:
        out = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT,
                             capture_output=True, text=True, check=True)
        return out.stdout.strip() or "dev"
    except Exception:  # noqa: BLE001 — not a git checkout
        return "dev"


def _package(built: str, out_dir: str) -> str:
    """Wrap the built binary in the goreleaser-style archive (zip+eds.exe on Windows, else tar.gz+member `eds`)."""
    os_name = platform.system()  # Windows / Linux / Darwin
    arch = _ARCH.get(platform.machine().lower(), platform.machine().lower())
    base = f"eds_{os_name}_{arch}"
    if os_name == "Windows":
        out = os.path.join(out_dir, base + ".zip")
        with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as zf:
            zf.write(built, arcname="eds.exe")  # _extract picks the first *.exe entry
    else:
        out = os.path.join(out_dir, base + ".tar.gz")
        with tarfile.open(out, "w:gz") as tf:
            tf.add(built, arcname="eds")  # _extract picks the member named exactly "eds"
    return out


def main(argv: list[str]) -> int:
    version = _resolve_version(argv)
    version_file = os.path.join(ROOT, "eds", "_version.py")
    with open(version_file, "w", encoding="utf-8") as f:
        f.write(f'# Generated by packaging/build.py — do not commit.\nVERSION = "{version}"\n')
    print(f"baked version {version} -> {version_file}")

    try:  # PyInstaller bundles eds._version from the source tree; remove it after so dev runs revert to "dev".
        rc = subprocess.run(
            [sys.executable, "-m", "PyInstaller", "eds.spec", "--clean", "--noconfirm"], cwd=ROOT
        ).returncode
    finally:
        os.remove(version_file)
    if rc != 0:
        return rc

    built = os.path.join(ROOT, "dist", "eds.exe" if platform.system() == "Windows" else "eds")
    if not os.path.exists(built):
        print(f"error: expected build output not found: {built}", file=sys.stderr)
        return 1
    artifact = _package(built, os.path.join(ROOT, "dist"))
    print(f"packaged {artifact} ({os.path.getsize(artifact) // (1024 * 1024)} MB)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
